
name: C/C++ CI

on: push

jobs:
  build:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2
    - name: do fetch to get all available tags/names
      run: git fetch --tags --depth=500 && git pull --tags && git --version
    - name: debug git describe 
      run: git describe --first-parent && git describe --first-parent --tags --always --match [0-9]*\.[0-9]*\.[0-9]*\-* 
    - name: prepare_os part 1
      run: sudo apt-get update -qq
    - name: prepare_os part 1
      run: sudo apt-get install -qq
            alien bison++ bisonc++ cmake doxygen freeglut3-dev flex gettext
            libboost-all-dev libc6 libc6-dev libcap-dev libfreetype6 libfreetype6-dev
            libgdbm-dev libgeos-dev libgeos++-dev libgif-dev libgtest-dev
            libjpeg-dev libjpeg8-dev libmng-dev libogdi3.2-dev g++ patch
            libpcre3 libpcre3-dev scons autoconf automake dpkg libtool build-essential
            libperl4-corelibs-perl libpng12-0 libpng12-dev libpq-dev libproj-dev
            libstdc++6 libtool libgif-dev libtiff-dev libgtk2.0-dev libglib2.0-dev
            libx11-dev libxcursor-dev libxerces-c-dev libxft-dev libxinerama-dev
            libxml2-dev libxml2-utils libxmu-dev libxrandr-dev libyaml-cpp-dev libpcre3-dev
            openssl shunit2 git git-lfs libqt4-dev qt4-default libqt4-opengl-dev
            python-dev python-git python-imaging python-setuptools python-psycopg2 python-lxml
            swig xorg-dev zlib1g-dev
    
    - name: build third party
      run: CPP_STD=11 BUILD_TYPE=release scripts/ci/build_third_party.sh
    - name: build fusion and test
      run: scripts/ci/build_fusion_and_test.sh
      env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


# cache:
#  timeout: 1200
#  directories:
#    - $HOME/cache

# notifications:
#  slack: opengee:YjzzzTnc7pgITPsrQPATIGwc
